apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::348476770446:role/Taiyi_Worker_Nodes
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::348476770446:role/SSO_SAML_Admin
      username: admin:{{SessionName}}
      groups:
        - system:masters
    - rolearn: arn:aws:iam::348476770446:role/SSO_SAML_Engineer
      username: engineer:{{SessionName}}
      groups:
        - system:masters
    - rolearn: arn:aws:iam::348476770446:role/SSO_SAML_Intern
      username: intern:{{SessionName}}
      groups:
        - system:masters